name: Publish Package

on:
  release:
    types:
    - published

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        # os: [windows-2019, ubuntu-18.04] # TODO: fix flakey tests that rely on DirectoryHelper
        # os: [windows-2019, ubuntu-18.04, macOS-10.14] # TODO: enable macOS once setup-dotnet has been fixed
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1

    # - uses: actions/setup-dotnet@v1 # TODO: enable once setup-dotnet has been fixed to explicitly set version
    #   with:
    #     dotnet-version: '3.0.100'

    - name: Install sample project dependencies
      run: dotnet run -p ./src/Regi/Regi.csproj -- install --configuration ./src/Regi.Test/_SampleProjects_

    - name: Run xunit tests
      run: dotnet test ./src/Regi.sln

    - name: Build with dotnet
      run: dotnet pack --configuration Release --output nupkgs ./src/Regi

  publish:
    name: Publish package
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1

    - name: Create NuGet package
      run: |
        REF="${{ github.ref }}"
        FILTER="refs/tags/v"
        export VERSION="${REF//$FILTER}"
        echo "Building Regi v${VERSION}"
        dotnet pack --configuration Release --output nupkgs ./src/Regi

    - name: Publish NuGet package ${{ github.ref }}
      run: |
        PACKAGE=$(find ./nupkgs/ -name "Regi.*.nupkg")
        dotnet nuget push $PACKAGE -k ${{ secrets.NuGetApiKey }} -s https://api.nuget.org/v3/index.json
