name: Run Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-18.04]
        # os: [windows-2019, ubuntu-18.04] # TODO: fix flakey tests that rely on DirectoryHelper
        os: [windows-2019, ubuntu-18.04, macOS-10.14] # TODO: enable macOS once setup-dotnet has been fixed
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install sample project dependencies
      run: dotnet run -p ./src/Regi.CommandLine/Regi.CommandLine.csproj -- install --configuration ./samples

    - name: Run xunit tests
      run: dotnet test ./Regi.sln
